version: '3'
services:
  app:
    build: C:/Users/levgr/git/образовач/spring-course-actual/spring-with-thymeleaf
    ports:
      - "8082:8082"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: capmorgan
    ports:
      - "5432:5432"